# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mbti?characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081