server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mainboard?serverTimezone=Asia/Seoul
    username: root
    password: 1111
